---
- name: Create Admin User
  user: name=admin password={{admin_password}} groups=sudo append=yes shell=/bin/bash

- name: Create Deploy User
  user: name=deploy password={{deploy_password}} groups=www-data append=yes shell=/bin/bash

# SSH Key Administration Needed